disks:
  - target_zone: northamerica-northeast2-c
    disk_name: vm-2
    disk_type: pd-ssd
    disk_size_gb: 20
    src_project_id: nodal-spot-453817-i7
    src_snapshot_name: docker-deploy-northamerica-nort-20250415204839-ln3blgl8
