# .github/workflows/pull-request-trigger.yml
name: Pull Request and Push to Main Trigger

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run a sample script
        run: echo "Triggered by PR or Push to main!"
